<?php

return [
    [
        'roles' => 'Super User|Admin|Contact',
        'permissions' => 'Contact',
        'name' => 'Contact',
        'route' => 'cms.contact.index',
        'icon' => 'fas fa-phone',
        'table' => 'contacts',
        'sidebar' => true,
        'subMenus' => [],
    ],
    [
        'roles' => 'Super User|Admin|Article',
        'permissions' => 'Article',
        'name' => 'Article',
        'route' => 'cms.article.index',
        'icon' => 'fas fa-newspaper',
        'table' => 'articles',
        'sidebar' => true,
        'subMenus' => [],
    ],
    [
        'roles' => 'Super User|Admin|Banner',
        'permissions' => 'Banner',
        'name' => 'Banner',
        'route' => 'cms.banner.index',
        'icon' => 'fas fa-images',
        'table' => 'banners',
        'sidebar' => true,
        'subMenus' => [],
    ],
    [
        'roles' => 'Super User|Admin|Slider',
        'permissions' => 'Slider',
        'name' => 'Slider',
        'route' => 'cms.slider.index',
        'icon' => 'fas fa-sliders',
        'table' => 'sliders',
        'sidebar' => true,
        'subMenus' => [],
    ],
    [
        'roles' => 'Super User|Admin|Store',
        'permissions' => 'Store',
        'name' => 'Store',
        'route' => 'cms.store.index',
        'icon' => 'fas fa-store',
        'table' => 'stores',
        'sidebar' => true,
        'subMenus' => [],
    ],
    [
        'roles' => 'Super User',
        'permissions' => 'Configuration',
        'name' => 'Configuration',
        'route' => 'cms.configuration.index',
        'icon' => 'fas fa-gears',
        'table' => null,
        'sidebar' => true,
        'subMenus' => [
            [
                'roles' => 'Super User',
                'permissions' => 'Configuration',
                'name' => 'Configuration',
                'route' => 'cms.configuration.index',
                'icon' => 'fas fa-gears',
                'table' => null,
                'sidebar' => false,
            ],
            [
                'roles' => 'Super User',
                'permissions' => 'Activity',
                'name' => 'Activity',
                'route' => 'cms.configuration.activity',
                'icon' => 'fas fa-history',
                'table' => 'activity_log',
                'sidebar' => true,
            ],
            [
                'roles' => 'Super User',
                'permissions' => 'User',
                'name' => 'User',
                'route' => 'cms.configuration.user.index',
                'icon' => 'fas fa-user',
                'table' => 'users',
                'sidebar' => true,
            ],
            [
                'roles' => 'Super User',
                'permissions' => 'Role',
                'name' => 'Role',
                'route' => 'cms.configuration.role.index',
                'icon' => 'fas fa-briefcase',
                'table' => 'roles',
                'sidebar' => true,
            ],
            [
                'roles' => 'Super User',
                'permissions' => 'Permission',
                'name' => 'Permission',
                'route' => 'cms.configuration.permission.index',
                'icon' => 'fas fa-key',
                'table' => 'permissions',
                'sidebar' => true,
            ],
            [
                'roles' => 'Super User',
                'permissions' => 'Setting',
                'name' => 'Setting',
                'route' => 'cms.configuration.setting.index',
                'icon' => 'fas fa-gear',
                'table' => 'settings',
                'sidebar' => true,
            ],
        ],
    ],
];
